### ISSUE TITLE
Add 'cursor', and 'hover' for 'fa' elements in 'app.css'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/interview-meetup#22]
We will define the following in `app.css`:

``` css
...
.figureset-button .fa {
  cursor:pointer;
}

.figureset-button .fa:hover {
  color:#D62A2A;
}
...
```
